### ISSUE TITLE
dynamic addressName support?

### ISSUE THREAD

**Issue by jkyeo** [JadianZheng/JAPing#1]
If I create JAPing instance in viewDidLoad() func and then start. it not work.

**Comment by JadianZheng** [comment]
# Do you keep the instance?

### If YES, you can try catch the error, use follow: 
```objc
-(nonnull instancetype)initWithHostName:(NSString* _Nonnull)hostName unexpertError:(ErrorHandle _Nullable)errorHandle NS_DESIGNATED_INITIALIZER;
```

**Comment by JadianZheng** [comment]
哦，你是南京的呀。
那普通话了。
你的标题问题不对应的，没看懂你的标题。

**Comment by jkyeo** [comment]
@JadianZheng  不知道该怎么表述，我目前是这样的，已经解决了：
<img width="609" alt="image" src="https://user-images.githubusercontent.com/4645158/55541746-29857100-56f8-11e9-8b35-cf036327cd3e.png">
<img width="394" alt="image" src="https://user-images.githubusercontent.com/4645158/55541760-33a76f80-56f8-11e9-8561-0e8256e01994.png">

也就是说，如果在上面这个ping 方法里创建JAPing 对象的话，start 是不工作的。但是如果在AppDelegate（或者ViewController）里创建，然后调用ping 方法时传进去就是正常的。

**Comment by JadianZheng** [comment]
在上面那样创建，肯定是会被释放掉的，pinger，我的库里面并没有一个manager去管理它，必须你本身使用者去持有。
所以你上面那样创建后，必须有个对象去长期持有，然后这个对象必须长期存在，至少在ping完成它的工作期间。

**Comment by JadianZheng** [comment]
很高兴，听到你解决了问题。后续有其它问题，欢迎提出
